### ISSUE TITLE
Cliping

### ISSUE THREAD

**Issue by Mrmiaou** [pizzaoverhead/FreeIva#216] opened 2023-02-18 21:40 UTC
So when I get up from the seat, I clip trough the plane and the ground. I fall to infinity. It's the same thing in orbit.
Is there a solution? Is the mod installed wrong? 
I installed it on Curse Forge.

**Comment by JonnyOThan** [comment] 2023-02-18 23:30
Please post your KSP.log file.  I'm going to close this because it's almost certainly an installation issue and not a bug in FreeIva, but if you provide your log file I can tell you what's going wrong.

I don't think curseforge has the latest version (pizzaoverhead manages that page).  You should download from here, spacedock, or ckan.

**Closed by JonnyOThan** 2023-02-18 23:30 UTC

**Comment by Mrmiaou** [comment] 2023-02-19 10:41
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/10776637/KSP.log)
Here, thanks for the help.

**Comment by JonnyOThan** [comment] 2023-02-19 12:56
Yeah there are a few problems:
1) You don't have the modulemanager dll.  You DO have some of its cache files, so maybe you deleted the dll at some point?  It's required for FreeIva.
2) FreeIva is installing in the wrong location.  When a mod's zip file contains a GameData folder, it means you're supposed to merge that with your own GameData folder.  You should never have a GameData folder inside GameData.
3) You're a few versions behind on FreeIva.

All of these would be fixed by using CKAN.

**Comment by Mrmiaou** [comment] 2023-02-19 13:11
Thanks for your help, I deleted the modulemanager because the version was in 8.1, I also installed it on curseforge.

**Comment by JonnyOThan** [comment] 2023-02-19 14:00
Yeah curseforge is pretty terrible for ksp mods, it contains a lot of out of date stuff and often installs things incorrectly.  CKAN is the preferred mod manager for KSP.
