### ISSUE TITLE
interior/airlock bug or gitch

### ISSUE THREAD

**Issue by KassIsLegend** [pizzaoverhead/FreeIva#371] opened 2023-11-28 19:10 UTC
interior overlay is turned off, this station was sent up in 2 seperate parts and all is fine and lagg free until i either stage or undock with a docking port then this happens sometimes the craft just spawns on the launchpad like this. Either or, it causes my framerate to tank everytime, in the pictures below im pulling about 15-20 fps and its been as low as 10-13 on the moon as i have this same station around the moon. This seems to happen with any part it thinks is an airlock, see attatched photos. In the attatched video the overlay glitch goes away when i undock and switch to starship but the moment i dock back to the station, the overlay glitches as seen and my framerate tanks to the floor. 

Video showing bug: https://www.youtube.com/watch?v=y3tNOi3e9SQ

Specs:

CPU: Ryzen 5 3600X @ 4.20Ghz
 
RAM: 16GB DDR4 @2400 MHZ

GPU: Zotac 1080TI 11GB

![Kerbal Space Program Screenshot 2023 11 28 - 09 16 30 75](https://github.com/pizzaoverhead/FreeIva/assets/65137073/a9f8c49f-8d4a-4353-9937-152dff72d553)
![Kerbal Space Program Screenshot 2023 11 28 - 10 56 00 39](https://github.com/pizzaoverhead/FreeIva/assets/65137073/dc08ceb1-6559-4f21-a4af-c5f517d9fda6)
![Kerbal Space Program Screenshot 2023 11 28 - 11 06 38 59](https://github.com/pizzaoverhead/FreeIva/assets/65137073/296d0b45-7cec-4522-9a7e-c171429d80df)

![Kerbal Space Program Screenshot 2023 11 28 - 09 04 45 07](https://github.com/pizzaoverhead/FreeIva/assets/65137073/bb36a420-c96a-48b9-adbb-6337d0b0c7a5)

**Comment by JonnyOThan** [comment] 2023-11-29 00:42
Please provide your ksp.log file with all bug reports or requests for support.  If you can send craft files that reproduce the issue, even better.

If you have JSI Transparent Pods installed, that will cause the overlays of centrifuge parts to render when they shouldn't.  But I don't think it would have much effect on performance.  Rather I suspect that at some times, the internals of the station are not created but doing certain actions is causing them to spawn, which is considerably rough on performance.  Still, if I had the craft file I could hook it up to the profiler and see if there's any low hanging fruit for optimization.

**Comment by KassIsLegend** [comment] 2023-11-29 01:22
removing JSI Transparant pods fixed the issue, thank you!

**Comment by JonnyOThan** [comment] 2023-11-29 01:34
Ok, dupe of #228 then

**Closed by JonnyOThan** 2023-11-29 01:34 UTC
Labels: duplicate
