### ISSUE TITLE
Kerbal seated in InlinePort disappears if...

### ISSUE THREAD

**Issue by numberlesstim** [pizzaoverhead/FreeIva#398] opened 2024-03-02 17:10 UTC
...original seat is occupied and original part has at least one empty seat.

Repro:

1. Spawn a Mk2 Cockpit with an inline dockingport and 2 Kerbals.
2. Move one kerbal to the inline port seat
3. Move the other Kerbal to the other Kerbals original seat
4. F5/F9
5. The Kerbal seated in the inline port has become invisible (still part of the crew if you recover at this point)
6. Move the Kerbal to the other seat again
7. F5/F9
8. Both Kerbals are available again

**Comment by JonnyOThan** [comment] 2024-03-02 19:08
dupe of #380

**Closed by JonnyOThan** 2024-03-02 19:08 UTC
Labels: duplicate
